version: 2
jobs:
  build:
    docker:
    - image: imulab/soteria-builder:latest
    branches:
      only:
      - master
      - development
    working_directory: /go/src/github.com/imulab/soteria
    steps:
    - checkout
    - run:
        name: Ensure dependencies
        command: dep ensure
    - run:
        name: Tests
        command: go test -v ./...
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Build docker image
        command: docker build -t imulab/soteria:latest .
    - run:
        name: Push image to docker hub
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push imulab/soteria:latest
